# Generated by Django 5.0.6 on 2024-06-10 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 6, 10, 0, 2, 26, 252962)
                    ),
                ),
            ],
        ),
    ]
